### ISSUE TITLE
Extension not available for on premisis installation

### ISSUE THREAD

**Issue by maltevesper** [hanneswidrig/azure-devops-pull-request-center#10]
Hello,
when we tried to install your extension for our on premisis setup, we noticed that we could not find it in the marketplace, since it is marked as available for 'Azure DevOps Services' but not marked as available for `Azure DevOps Server`. Since the extension you forked from is available for on premisis installation, we are going to run with that for now. Could you please consider enabling the on premisis installation?
Kind regards,
Malte Vesper

**Comment by hanneswidrig** [comment]
Hey Malte,

I've modified the configuration json as of **1.2.7,** it should be available for Azure DevOps Server now. If you have any issues, let me know.
