### ISSUE TITLE
License misses original copyright notice

### ISSUE THREAD

**Issue by maltevesper** [hanneswidrig/azure-devops-pull-request-center#11]
Although I am not a legal expert, I think one should extend the courtesy of not only mentioning the roots promenently in the readme as this project does, but also add it to the license file. The MIT license reads "**The above copyright notice** and this permission notice shall be included in all
copies or substantial portions of the Software." after all.

**Comment by hanneswidrig** [comment]
Sorry I am a bit confused, what exactly are saying should be added to the license file?

**Comment by maltevesper** [comment]
I would suggest that the License file carries the following entries:

```
Copyright (c) 2019 Carlos Alessandro Ribeiro
Copyright (c) 2019, 2020 Hannes Widrig
```

since if I read the history correctly your very nice Improvements are based on Alessandro Ribeiro's work. If I am mistaken, I am sorry for the hussle, otherwise I hope I just pointed out a potential oversight.

**Comment by hanneswidrig** [comment]
Understood, I used his project as a starting point for constructing my own extension, the license he has on his project doesn't require credit. Thanks anyways
