### ISSUE TITLE
Extension can take several seconds to load into view

### ISSUE THREAD

**Issue by ghost** [hanneswidrig/azure-devops-pull-request-center#13]
Hello, 

This is a really great extension and I appreciate the separate tabs for Active/Drafts/Completed. However, loading the extension can take between 6-10 seconds on average, maybe because the Recently Completed section pulls in 800+ PRs for my organization. 

In our case, we have more than 1 repo and many are archived so we have really old results popping up in the Completed view. It would be great if there were a setting to disable that tab or have all tabs be lazy loaded - for the most part we're interested in the Active tab and will rarely go to Recently Completed.

Thanks!

**Comment by hanneswidrig** [comment]
Thanks for the input, I like the idea of lazy loading completed pull requests. I also wanted (when I had time) to improve the completed tab UX since it's currently pulling the most recently 25 pull requests from each project.

**Comment by hanneswidrig** [comment]
Hey @stemidy , my latest release should help you out. I went with the lazy loading approach for now as other desired changes I would like require more work than I have time for.

You'll be presented with Active/Draft PRs, while the recently completed PRs are quietly fetched in the background. Once they load, you'll know by the number that appears next to Recently Completed.  
![image](https://user-images.githubusercontent.com/3399497/87866546-22b45900-c951-11ea-8301-f420259703d8.png)

**Comment by ghost** [comment]
Thanks, @hanneswidrig! I appreciate the quick response; this works nicely and the view is now loading much quicker.

Cheers!
