### ISSUE TITLE
Saved filters are cleared when loading the page

### ISSUE THREAD

**Issue by Galad** [hanneswidrig/azure-devops-pull-request-center#16]
First, thanks for this extension, it is very nice seems to do the job for us.
We are trying to have a place where developers can find the pull requests they have to review. Developers can be part of a group that is assigned to pull requests (using reviewer policies). Using the `Reviewers `filter, and selecting the groups I belong to, while filtering `My approval status` with `Assigned`, and saving it, I can do that.

However we encounter an issue. The steps are the following:
- Add filters
- Save the filters
- Reload the page
- Wait for the list to load
- Observe that the saved filters are there, and the list is properly filtered
- Wait a few seconds (or click the Refresh button)
- Observe the filters are cleared without any action and the list is reloaded

Browers: Edge Chromium 89.0.774.4, Chrome 88.0.4324.104

**Comment by hanneswidrig** [comment]
Hey Lucas, thanks for submitting this bug report. When I have time, I will attempt to solve this bug, can't promise any timetable.

**Comment by fredrik-hellmangroup** [comment]
unfortunately i also have this issue but nice extension!

**Comment by hanneswidrig** [comment]
I've not had the time to support the extension further, I will work with any pull requests that are created in attempting to fix issues.

**Comment by cheesi** [comment]
First of all: thank you very much for this very nice extension!

Just installed it today and unfortunately we are suffering from the same issue :(

I can see there is already a pull request to fix the issue?
Would be really nice, if this would get released in the near future 😊
