### ISSUE TITLE
Possibility to filter on non-active values

### ISSUE THREAD

**Issue by fredrik-hellmangroup** [hanneswidrig/azure-devops-pull-request-center#17]
First, thanks for this extension, it is very nice!

I'm seeing that i can only select and save a filter based on what's present in the PR table view. This is fine when filtering on current items but for setting up a saved filter this is a limitation

Suggestion is to have a background lookup towards azure devops rest api for query out additional info.

Columns we are most interested in are:

- Repositories
- Reviewer

**Comment by hanneswidrig** [comment]
Hopefully the behavior is a bit less jarring in the v2.0.0 update, however for now I'll stick with relying on pull request data returned for the source of filtering criteria.
