### ISSUE TITLE
Possibility to limit Completed PR's history view 

### ISSUE THREAD

**Issue by fredrik-hellmangroup** [hanneswidrig/azure-devops-pull-request-center#18]
Current implementation seem to list pr's that goes about a bit over 1 year in history. Currently for our solution this is 276 PRs
It would be nice to have a filter for this view only that you can filter out entries older than X days (7,14,30, user defined)

![image](https://user-images.githubusercontent.com/13755193/115571028-e5557100-a2be-11eb-9f4d-610492913001.png)

in addition there seem to be a mix of how how far back you currently fetch the history in respective git repo (check dates)
![image](https://user-images.githubusercontent.com/13755193/115571435-4715db00-a2bf-11eb-8a9e-3fa61646c1ce.png)

**Comment by hanneswidrig** [comment]
Would you be willing to assist in beta testing the 2.0 release once it's ready?

**Comment by fredrik-hellmangroup** [comment]
@hanneswidrig  Yep i see no reason why i shouldnt :)

**Comment by hanneswidrig** [comment]
@surfaace Please install the beta release I have created, https://marketplace.visualstudio.com/items?itemName=hannes-widrig.azure-devops-pull-request-center-beta. It would be easiest to message back and forth on a messaging platform like telegram. I'll be looking for general feedback and if there's any bugs.
