### ISSUE TITLE
Pull requests not loadable for disabled repositories

### ISSUE THREAD

**Issue by MarioCakeDev** [hanneswidrig/azure-devops-pull-request-center#20]
When a repository is disabled the pull requests cannot be loaded. The request to get the pull requests fails with following error message:

_"TF401019: The Git repository with name or identifier [GUID] does not exist or you do not have permissions for the operation you are attempting."_

The UI will only show a toast with the error message "An error occurred while fetching pull requests. Please reload or refresh the page."

The disabled repositories need to be filtered before they will be used to get the pull requests.

I don't have any admin permissions so this might be the reason why I can't see it. But I'm expected just not to see the Pull Requests of disabled Repositories instead of getting an error.

**Comment by hanneswidrig** [comment]
I'll look into a solution for this, thanks for reporting it.
