### ISSUE TITLE
Looking for Beta Testers

### ISSUE THREAD

**Issue by hanneswidrig** [hanneswidrig/azure-devops-pull-request-center#21]
v2.0.0 is currently in beta and can be accessed [here](https://marketplace.visualstudio.com/items?itemName=hannes-widrig.azure-devops-pull-request-center-beta).

Please leave any and all feedback within this issue.

**Comment by cheesi** [comment]
Hey!

I installed the beta version and found a bug:
If you select (f. e.) multiple repositories, it can happen that the element is cut off:
![image](https://user-images.githubusercontent.com/5590254/147162815-9e1ce69c-9b39-4ae4-8156-c48f427037e8.png)
(to specify: in this case, I can see the full name of the second repository, but there is no padding, and also no `x` button to remove just that specific filter)

Systeminfo: Windows 11 / Firefox 95.0.2

**EDIT:**
It looks like it is always cut of (added three repos in this case):
![image](https://user-images.githubusercontent.com/5590254/147163071-6c98def6-67ee-4a46-a50e-ed69b2ffea66.png)

If I click into the field, it then jumps to the end, so in my case only the last two repositories (first of those two is cut off) are visible:
![image](https://user-images.githubusercontent.com/5590254/147163191-caef6c9a-a2fc-4c01-ad29-8f33118253d6.png)

**Comment by cheesi** [comment]
My name is automatically wrapped on two columns in the author column, even though, there is more than enough space from the title column.
![image](https://user-images.githubusercontent.com/5590254/147163384-86a356dd-7cd4-4b64-b441-299870848809.png)

Systeminfo: Windows 11 / Firefox 95.0.2
Display: 34", 3440x1440 (also tested on a 27", 3840x2160)

Also the Source branch column is cut off. Maybe it would also happen with the Target branch (f. e. if we would have merges to release branches with a longer name like release/3.1). Repository name is also cut off.

**Comment by cheesi** [comment]
Author filter doesn't show the name, only the icon:
![image](https://user-images.githubusercontent.com/5590254/147164127-0691dfef-2b90-4125-8686-9d99d5953ff9.png)

Systeminfo: Windows 11 / Firefox 95.0.2

EDIT: same thing for the columns Reviewer and Approval Status

If this is on purpose, please think about, that there can be users without a profile picture and they can have the same color like in this case:
![image](https://user-images.githubusercontent.com/5590254/147165773-8c1d74a2-a9ff-4e5a-a0c2-626626fd7a54.png)
And then they are really hard to recognize by just the two small letters.

**Comment by cheesi** [comment]
New filter bar doesn't really work well with small displays (just moved the whole browser window to the left half of my 34" screen, so it is basically an "old 4:3" window now):
![image](https://user-images.githubusercontent.com/5590254/147164305-e8f9d717-a142-4d01-b1bd-54e73f3f9f8c.png)

Fields have different highs, filter selection is not really visible. The old UI element was a little bit better here, especially because you could just open the drop down and see the selected filters.

Systeminfo: Windows 11 / Firefox 95.0.2

**Comment by cheesi** [comment]
Also it would be nice to have two different settings for the "Days ago".
For example, I would like to see always all open PRs.
However, the completed PRs would be fine f. e. with only 7 days, or maybe the length of the sprint (so an option with 3 weeks in our case would also be cool, but not absolutely necessary as a month is also fine).

Also it might be nice to have a combo box, instead of radio buttons for the configuration to save some space:
![image](https://user-images.githubusercontent.com/5590254/147164952-b493d6f7-3f76-4c2e-a89c-d34f9e44ca73.png)

Also the default config of 7 days (especially for Open PRs) is quite low. Especially if you work in a bigger organization, where PRs might take a week or two to merge.

**Comment by cheesi** [comment]
The console logs some permission errors, when I open the Pull Request Center:
![image](https://user-images.githubusercontent.com/5590254/147165375-ab8c766f-4d46-4a98-b358-c7d34c25e455.png)

The blurred parts are Guids.
My user is an the organization administrator. Also tested it with another user (just project administrator), I also got some permission errors there.

**Comment by cheesi** [comment]
The auto refresh interval setting is missing some bottom/top padding (comparison new vs. old)
![image](https://user-images.githubusercontent.com/5590254/147166560-108f2170-5d68-4557-8dac-fd2f78fe771b.png)
![image](https://user-images.githubusercontent.com/5590254/147166585-4b114eaa-202d-4a30-96bb-fc275baa131c.png)

**Comment by cheesi** [comment]
Also a question: are these settings (=Extenstions Preferences) saved for the current user? or the current project? or for the whole organization?

**Comment by hanneswidrig** [comment]
Hey @cheesi I'll try to address all your feedback and we can explore solutions if needed. I've numbered each concern.

1. You can scroll horizontally which I realize now is something that works great on Macs with a trackpad, but for a mouse and keyboard might not be a very obvious or desirable experience. I can explore ways to more clearly display the options and make them select/de-selectable.

![image](https://user-images.githubusercontent.com/3399497/147186393-e5c1b154-cde9-4cbe-a7f8-cfbd41c317fa.png)


2. I struggled on the best approach for handling the endlessly variable length of characters for the columns, the full text content is displayed on hover, also every column is adjustable, this isn't saved on reload unfortunately which I can see as an annoyance/issue.

![image](https://user-images.githubusercontent.com/3399497/147186360-7a86d79b-6b98-497e-af09-fa350263e916.png)

3. I'd love some feedback on a better way to represent the variety of users, I could include the names too if that's the only difference. A potentially better solution to the multi-select selection display would resolve some of those concerns.

4. I was hoping for feedback about the responsiveness of the filters, I'm concerned about why it doesn't appear to be wrapping for you, at 1024px, it should wrap to two line solution like this.

![image](https://user-images.githubusercontent.com/3399497/147186629-94ab8fdc-60cc-44cf-a373-05d367b4ee54.png)

5. I like the combo box instead, I also have no concerns about upping the default config, to at least 14 days by default. That would be a normal sprint (14 days).

6. Don't worry about these errors, Microsoft has never provided an answer to what exactly can be done about them for years now, they don't appear to affect anything.

7. I'll look into fixing the padding on that component.

8. Extension preferences are saved "per user", so your settings will only be saved for your login `john_doe@my_company.com`.

**Comment by hanneswidrig** [comment]
@cheesi I think we'll both be huge fans of Microsoft's `<ComboBox ... />` solution. 
![image](https://user-images.githubusercontent.com/3399497/147189191-eab2f014-2e39-47c2-b800-2bd89357f30f.png)

**Comment by cheesi** [comment]
Hey! 
Thank you for you very quick response.

1. Unfortunately horizontal scrolling doesn't work at all in my case :( There is no horizontal scroll bar, mouse wheel also doesn't help. I can jump around with the cursor, however that will just move the course out of my view.
2. Yeah I also discovered this workaround. Would be a really nice, if those changes would be saved.
3. The Microsoft ComboBox also looks like a better solution for me in this case.
4. It looks like, that half of my screen, is just not small enough to switch to the two line filter bar. I did I quick testing, while noting ~pixels of the width:
    - 1592: approval status two lines
    - 1556: search box (empty)
    - 1492: source branch
    - 1463: target branch
    - 1372: half of my 34" screen
    - 1284: `s` of repositories is cut off
    - 1277: change to two line for the filter bar
5. Sounds great.
6. Alright, I just wanted to mention :)
7. Perfect
8. Okay, thanks for clarification. I have the feeling, that I lost my configuration (in V1 extension) and thought, okay maybe this is shared among the project.

**Comment by hanneswidrig** [comment]
@cheesi I've released beta `0.4.1`, when you get a chance, please verify most of the issues have been resolved. The only problem I really don't know how to easily solve is the table column widths defaulting to be narrow.

**Comment by cheesi** [comment]
Hi @hanneswidrig !

Thanks for the new version, looks really good.
Regarding the table column widths: unfortunately, I can't really help you with that one, as I'm not really a frontend dev.
From what I know, I would try to set the widths based on a grid system.

I found one new thing: I think it would make sense to sort the elements in the filter combo boxes:
![image](https://user-images.githubusercontent.com/5590254/147627748-d071e38c-2744-4792-afd6-71b86b54ce14.png)

`Repositories` and `Source Branch` are definitely affected, but of course this also makes sense for the other columns.

**Comment by hanneswidrig** [comment]
@cheesi Check out the sort order of the values inside the combo boxes, I just chose standard alphabetical order. It's in beta `0.4.2`.

I'm using Microsoft's table implementation and it doesn't appear to easily let me have the grid behave more accurately on initial load. I'll save that for a future release.

**Comment by cheesi** [comment]
Hey!

Thanks for the update, looks good :)

Regarding the table sizing: I can understand that. Would be nice to find a solution for that in the future.

One thing, which I just have noticed:
The source branch filter shows (in my case) over 400 entries in the "Active" tab, even though, we only have a handful of active pull requests. For me it looks like all branches (also from completed PRs) are listed here:
![image](https://user-images.githubusercontent.com/5590254/147720830-6a94767b-2e80-4660-a43c-58fd48bf4a78.png)

I would suggest, that the tab selection should also filter the available options from the filter bar.

**Comment by hanneswidrig** [comment]
@cheesi `0.4.5` should behave correctly, it creates some more complicated scenarios for when filters are saved, however I think I've handled those well.

**Comment by cheesi** [comment]
Hey!

Thanks for the Update, definitely looks cleaner now.
Regarding configuring and saving filters: I see now, why you need to handle some extra stuff there. I guess, that maybe there would be some potential features for the future, like configuring branches, which are currently not selectable. But for me that's more a nice to have.

Also I found a small styling issue, if there are no pull requests:
![image](https://user-images.githubusercontent.com/5590254/148025110-e3b38b9e-7db0-451d-8cdb-9b4e0deee867.png)

**Comment by hanneswidrig** [comment]
@cheesi Alright I think everything is working as expected now with `0.4.6`. When you get a chance please run through and check if you see any obvious problems appear. I think I am about ready to release v2.0.0 assuming everything looks good.

Thanks again for all the useful feedback, I'm really excited to see how this new version improves workflows.

**Comment by cheesi** [comment]
Hey!

Thanks for the fix, looks really nice now. Everything looks good from my side, so yes, I also have the feeling that you can go forward with the v2 release.

> Thanks again for all the useful feedback

You are very welcome. Thank you for all your hard work on this extension!

**Comment by hanneswidrig** [comment]
# @cheesi v2.0.0 has been released! 🎉
