### ISSUE TITLE
The background is blank with dark mode theme

### ISSUE THREAD

**Issue by rodrigokono** [hanneswidrig/azure-devops-pull-request-center#22]
Using Azure DevOps with dark mode theme (Dark, neptune, etc) the plugin backgroung stay in blank.

**Comment by Logikoz** [comment]
UP!

![image](https://user-images.githubusercontent.com/37851168/148668580-3b4e9b9c-8efb-4553-9cac-0b21c99b0073.png)

**Comment by hanneswidrig** [comment]
@rodrigokono and @Logikoz , do you mean the table and the filtering options should be "dark mode" compatible?

**Comment by rodrigokono** [comment]
yes. before the last update this was good.
maybe changed the reference for theme styles of azure devops.

**Comment by hanneswidrig** [comment]
@rodrigokono Yep, I'll try to determine a solution, the DevOps UI gives me no way to easily identify whether you've toggled dark mode, there's some private internals for older components that tied into the dark mode status or not.

**Comment by hanneswidrig** [comment]
@rodrigokono and @Logikoz `v2.1.1` should contain the necessary fixes for dark mode themes.
