### ISSUE TITLE
Content not loading

### ISSUE THREAD

**Issue by LSTANCZYK** [hanneswidrig/azure-devops-pull-request-center#23]
Addin stopped working for one of the projects in my organization. 
It just spins on loading the PRs
![image](https://user-images.githubusercontent.com/2145721/148996428-1b830ce3-e8fd-4d2c-93be-e8432be47af3.png)

I do not see any errors in DevTools console.

Everything works just fine for other projects in the DevOps organization. 

I would be happy to provide more information if needed.

**Comment by hanneswidrig** [comment]
@LSTANCZYK Can you tell me what the network requests look like?

**Comment by cheesi** [comment]
I have the same issue now :(

![image](https://user-images.githubusercontent.com/5590254/149774741-234692f1-bcc2-4f76-a2d2-9f23a450a4d1.png)

It worked today in the morning, so it looks like it's a data driven bug. (as the last update of the extension was on Saturday)

**Comment by hanneswidrig** [comment]
Thanks guys, if it's not a console logged error or a network request error, that helps narrow down what is happening.

**Comment by hanneswidrig** [comment]
@cheesi Please let me know if you're still having issues, I released update v2.1.2 just now.

**Comment by hanneswidrig** [comment]
@LSTANCZYK and @cheesi, I've redone the loading scheme with v2.2.0. Please let me know if that fixes the loading issues you're experiencing. If we're experiencing request issues, those should be logged as errors now.

**Comment by LSTANCZYK** [comment]
It worked for me like a charm! Thank you!

**Comment by cheesi** [comment]
Hey @hanneswidrig !

Unfortunately, I still have the issue.
But the request pattern changed a little bit:
![image](https://user-images.githubusercontent.com/5590254/149816674-2cffc240-3956-4816-942a-f680a66140b2.png)

And no console logs.

**Comment by hanneswidrig** [comment]
@cheesi Do the "GET" responses for pull requests look like actual data or is it empty? 
![image](https://user-images.githubusercontent.com/3399497/149818804-54402198-b07c-4afe-a9d1-b4fda3577bc8.png)

Also I see that you're using Firefox, have you attempted to load the extension in Google Chrome or Edge?

I've released `v2.2.2` which will `console.error` when there are Promise rejections and `console.log` successful redux actions.

**Comment by cheesi** [comment]
Hey!

I guess the response was empty, as you can see from the last column (size).

However, it is working now.

ADO just updated the extension:
![image](https://user-images.githubusercontent.com/5590254/149820796-0f330b6e-8f01-45fc-a3dc-149ef00ec44c.png)

So it looks like that was the issue.

**Comment by hanneswidrig** [comment]
@cheesi Sounds good, let me know if anything strange happens from here. I'm now logging when the redux actions fail or succeed like so.
![image](https://user-images.githubusercontent.com/3399497/149820913-8493d811-9449-4603-96eb-b195d2693ec6.png)

**Comment by iduras3** [comment]
I am currently running in the same Issue again, that the Page is not loading.

**Comment by cheesi** [comment]
Hey @hanneswidrig !
I'm a colleagues of @iduras3.

The redux messages are successful:
![image](https://user-images.githubusercontent.com/5590254/158402439-f4eb1637-a704-446c-9e37-ccbd1fb42e66.png)

Looks like the request to the backend just returns an empty array:
![image](https://user-images.githubusercontent.com/5590254/158402687-9bedddd3-2189-4594-8017-e2a5074c1446.png)
![image](https://user-images.githubusercontent.com/5590254/158402734-11f81158-fbbd-4a5f-8943-9d1618f63e97.png)

**Comment by iduras3** [comment]
I got a response with data as soon as I removed the paging part from the  URL. 
I think there is a problem with the dollar sign in the URL

**Comment by hanneswidrig** [comment]
@cheesi is it only @iduras3 who is having this issue? I assume the responses are working for you? If they do, can you compare if your `$skip` is as large as @iduras3's.

I also verified it's still working for me in my test DevOps instance.

**Comment by iduras3** [comment]
@hanneswidrig everyone in our team has the problem. The images are actually already from @cheesi  .

**Comment by hanneswidrig** [comment]
> @hanneswidrig everyone in our team has the problem. The images are actually already from @cheesi  .

Does it start paginating at 14,000 (skip) or so?

**Comment by cheesi** [comment]
I don't know about the other devs, I just can conform, that at least we both have the issue, but I guess everyone else too.

No it starts with 0, then 25, then 50 and so on.

As far as I can see the extension hasn't been updated since January (at least on our orga), I assume, that it is either a ADO issue or a data driven issue.

**Comment by hanneswidrig** [comment]
> I don't know about the other devs, I just can conform, that at least we both have the issue, but I guess everyone else too.
> 
> No it starts with 0, then 25, then 50 and so on.
> 
> As far as I can see the extension hasn't been updated since January (at least on our orga), I assume, that it is either a ADO issue or a data driven issue.

I haven't updated the extension since January so that's correct.

Is every result including those first 0, 25, 50 skip requests an empty array? I presume it is, are there other pull request extensions working for you?

**Comment by iduras3** [comment]
I am not sure, if @cheesi changed anything, but it seems to work again.

**Comment by iduras3** [comment]
After doing some PullRequests it stoped working again.
We get some results at the beginning of a reload, but it endlessly sends new requests with a higher skip

**Comment by cheesi** [comment]
> Is every result including those first 0, 25, 50 skip requests an empty array?

Yes, all of those API calls return an empty array.

> are there other pull request extensions working for you?

We don't really have any other Pull Request extensions. The normal PR overview (for a single repo) works as expected.

> I am not sure, if @cheesi changed anything, but it seems to work again.

I looks like it worked again for a few minutes. Now it doesn't. Very strange. 

Also there is currently an Availability Degradation ongoing, maybe that's the reason?
![image](https://user-images.githubusercontent.com/5590254/158537366-de6958a2-a4c4-4b5b-9464-498724096d84.png)

**Comment by hanneswidrig** [comment]
It its sometimes working and sometimes not, I think it might be the availability degradation, if those issues clear up and its still not working, I will investigate further.
