### ISSUE TITLE
Selected Filter Values are not saved per user

### ISSUE THREAD

**Issue by cheesi** [hanneswidrig/azure-devops-pull-request-center#24]
Back in https://github.com/hanneswidrig/azure-devops-pull-request-center/issues/21 I asked, if the user settings where saved per user, because I had the feeling, that the view was reset, which was confirmed.

Our Frontend teams is currently moving from a monorepo to a multirepo setup and also started using this extensions.
Now I definitly can confirm, that we are overriding each others values, as they configured a different default filter.

See your teams thread here:
![image](https://user-images.githubusercontent.com/5590254/169021823-52141832-714d-46be-8ab8-4d71ed0f52d7.png)

Would be really nice, if those values would be saved per user.

**Comment by hanneswidrig** [comment]
When I get some time I'll look into this, shouldn't be difficult to fix.

**Comment by hanneswidrig** [comment]
This should be fixed in 3.0.0. Please let me know if you see any additional issues.
