### ISSUE TITLE
Display Policies status

### ISSUE THREAD

**Issue by yannick-Lapierre** [hanneswidrig/azure-devops-pull-request-center#7]
Hello,
You made a very good tool!

If you are looking for suggestion, you may add an option to display the Policies status of the PR.

Regards,

**Comment by hanneswidrig** [comment]
Hello!

Thanks for your suggestion, this is not something I had thought of before but I can see the usefulness. When I have more time, I'll look into adding this feature.

**Comment by maltevesper** [comment]
For what it is worth, I added a picture how it looks like in pull request manager hub for inspiration.

![image](https://user-images.githubusercontent.com/10866845/83516770-f5face00-a4d7-11ea-810d-5772bdb2fbac.png)

**Comment by hanneswidrig** [comment]
This enhancement is indefinitely on hold, focused on fixing longstanding bugs with the filtering and fetching.
