### ISSUE TITLE
An error occurred while fetching pull requests. Please reload or refresh the page.

### ISSUE THREAD

**Issue by GerryWilko** [hanneswidrig/azure-devops-pull-request-center#8]
I cannot load the pull request center it just errors and continuously loads. Is there somewhere I can see the error to work out if its permissions or something?

Many thanks,
Gerard

**Comment by GerryWilko** [comment]
Just checked error console and it seems shared storage permssions is the problem. Cant see anywhere on DevOps I can grant access to this.

`No permissions found for security namespace "*********" and token "*********". Ensure that the effective permissions are included in shared data. ms.vss-web.platform-content.es6.T1WfB1Bq6sDuC5Cr.min.js:1:103199`

**Comment by hanneswidrig** [comment]
Thanks for creating this issue. I will look into the permissions I am currently requiring. This would explain why other uninstalls have complained about this error in the past. I never had the issue in my Azure DevOps instances.

**Comment by hanneswidrig** [comment]
Hey @GerryWilko,

That error message actually appears on all the other pull request dashboard extensions. Microsoft has been non-responsive with solutions. You can see this just by googling the error. This should not be preventing the pull request from loading.

What you could provide helpfully for me now would be to show me which network requests are failing for you.

![image](https://user-images.githubusercontent.com/3399497/77833983-bd292c00-7117-11ea-9ba1-c5c4a397f6bc.png)

Filter by XHR in chrome and then identify which endpoints failed.

**Comment by GerryWilko** [comment]
![image](https://user-images.githubusercontent.com/9151572/77889919-8d3c6e80-7266-11ea-9269-d40d77d65ec5.png)

There are individual requests for each pull request down below this that all return 200. It seems maybe one of those 404s or that 204 is unexpected?

**Comment by hanneswidrig** [comment]
@GerryWilko, I believe I found the issue, bit confused how it ever worked for anyone. Can you install version `1.2.5` and verify it fixes your problem.

Also, if it works, can you apply setting modifications and confirm they persist across browser restarts.
![image](https://user-images.githubusercontent.com/3399497/77979848-c828bb80-72d3-11ea-8ebd-f57c0d95609d.png)

**Comment by GerryWilko** [comment]
Brilliant thats fixed it! Also checked your settings persist and they seem to across browser restart on Firefox and Chrome.

Thanks for your help and great work!
